version: "3.8"
services:
  nuxtapp:
    build: .
    container_name: torkatatech_frontend
    ports:
      - "3000:3000"          # host:container
    environment:
      NODE_ENV: production
      NITRO_HOST: 0.0.0.0
      NITRO_PORT: 3000
      # contoh runtime config:
      # NUXT_PUBLIC_API_BASE: "https://api.example.com"
      # API_SECRET: "xxxx"
    restart: unless-stopped
    # optional: healthcheck biar gampang monitor
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:3000"]
      interval: 10s
      timeout: 3s
      retries: 5
